// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTMFNlWzHZkBa1AJzM7zGT7EFn5PUMK14',
    appId: '1:1030103229063:android:4ad0d50531d18fa4ba4e22',
    messagingSenderId: '1030103229063',
    projectId: 'normallab-82e25',
    storageBucket: 'normallab-82e25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJqM_kihJvd0MZiqpbwWd_38Sjqf9imI',
    appId: '1:1030103229063:ios:e6afb44924962ceeba4e22',
    messagingSenderId: '1030103229063',
    projectId: 'normallab-82e25',
    storageBucket: 'normallab-82e25.appspot.com',
    iosBundleId: 'com.example.projectLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJqM_kihJvd0MZiqpbwWd_38Sjqf9imI',
    appId: '1:1030103229063:ios:e6afb44924962ceeba4e22',
    messagingSenderId: '1030103229063',
    projectId: 'normallab-82e25',
    storageBucket: 'normallab-82e25.appspot.com',
    iosBundleId: 'com.example.projectLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-2-sHjkH-lulPya9NodPLp0spiR5AC5g',
    appId: '1:1030103229063:web:049efad3ab8ee3a9ba4e22',
    messagingSenderId: '1030103229063',
    projectId: 'normallab-82e25',
    authDomain: 'normallab-82e25.firebaseapp.com',
    storageBucket: 'normallab-82e25.appspot.com',
    measurementId: 'G-NZW3936WJ8',
  );

}